---
title: "R Programming Basics"
author: "Professor André Salerno, MSc"
date: 2019-03-30T21:16:14-05:00
categories: ["R"]
tags: ["R Markdown", "Basics", "Introduction"]
output: html_document
draft : FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, echo = TRUE, warning = FALSE, collapse = TRUE)
setwd("~/Documents/hugo-site/hugo-site/content/blog")
```

### SessionInfo

```{r a}
sessionInfo()
```


### Generates 100 random positive variates

```{r b}
data <- abs(rnorm(100))
mean(data)
```
### Simple Vector

```{r c}
x <- c(1, 2, 3, 4)
print(x)
```

### Adding Vector

```{r d}
y <- c(x, x, 5, 6, 7, 8)
print(y)
```

### Times between objects
```{r e}
z <- c(1, 2, 3, 4)

times <- x * z
print(times)

```
### Adding between objects
```{r f}
add <- x + z
print(add)
(add[2:3])

(mean(add))
(sd(add))
```

### Choosing the third element

```{r g}
print(add[3])
```

### Choosing object (except first and fourth element)

```{r h}
print(add[-1])

print(add[-4])

(add[-3]) #another print way (using parenthesis)
```

### Store/retrieve commands
```{r i}
(source("adding.R"))
```

### Batch Mode

```{r j}
pdf("xh.pdf") # set graphical output file
hist(rnorm(100)) # generate 100 N(0,1) variates and plot their histogram
dev.off() # close the graphical output file

#`$ R CMD BATCH z.R`
```

```{r k}
(mean(Nile))
(sd(Nile))
hist(Nile)
```

### Function

```{r l}
# counts the number of odd integers in x
oddcount <- function(x) {
  k <- 0 #assign 0 to k
  for (n in x) {
    if (n %% 2 == 1) 
      k <- k + 1 ## %% is the modulo operator
  }
  return(k)
}

oddcount(c(1,3,5))

oddcount(c(1,2,3,5,7,9))

```

### Matrices
```{r m}
m <- matrix(1:6, nrow = 3, ncol = 3, byrow = TRUE)
print(m)
class(m)
str(m)
summary(m)
colnames(m) <- c("A", "B", "C")
rownames(m) <- c("D", "E", "F")
print(m)

(p <- rbind(c(1:4), c(5:8)))

(u <- cbind(c(1:4), c(5:8)))

(c <- u %*% c(1,1))

(u <- cbind(u, c))

(colnames(u) <- c("A", "B", "A+B"))
rownames(u) <- c("C", "D", "E", "F")
```

### Concatenate

```{r}
(j <- paste("ABC", "DEF", "GHIJKLM")) # concatenate the strings
(v <- strsplit(j, " ")) #split the string according to blanks

```

